## 1.1 列表推导式与条件赋值

In [1]:
L = []

In [3]:
def my_func(x):
    return 2*x

In [4]:
for i in range(5):
    L.append(my_func(i))

In [5]:
L

[0, 2, 4, 6, 8]

从这一步我记住了def句末要加:（忘了会报错）

In [7]:
[my_func(i) for i in range(5)]

[0, 2, 4, 6, 8]

把for语句变一个形式写

In [8]:
[m+'_'+n for m in ['a','b'] for n in ['c','d']]

['a_c', 'a_d', 'b_c', 'b_d']

这一句是两层嵌套

In [9]:
value = 'cat' if 2>1 else 'dog'

In [10]:
value

'cat'

In [12]:
a, b = 'cat', 'dog'
condition = 2 > 1 # 此时为True
if condition:
    value = a
else:
    value = b
value

'cat'

In [13]:
L = [1, 2, 3, 4, 5, 6, 7]
[i if i <= 5 else 5 for i in L]

[1, 2, 3, 4, 5, 5, 5]

## 1.2 匿名函数与map用法

In [14]:
my_func = lambda x: 2*x
my_func(3)

6

lambda是啥意思？原来是省去函数名字的意思。

In [15]:
[(lambda x: 2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [16]:
list(map(lambda x: 2*x, range(5)))

[0, 2, 4, 6, 8]

In [17]:
list(map(lambda x, y: str(x)+'_'+y, range(5), list('abcde')))

['0_a', '1_b', '2_c', '3_d', '4_e']

这个形式对于初学者的我来说，已经很复杂了┭┮﹏┭┮

## 1.3 zip对象与enumerate方法

In [18]:
L1, L2, L3 = list('abc'), list('def'), list('hij')

In [19]:
list(zip(L1, L2, L3))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [20]:
tuple(zip(L1, L2, L3))

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))

In [21]:
for i, j, k in zip(L1, L2, L3):
    print(i,j,k)

a d h
b e i
c f j


In [22]:
L = list('abcd')
for index, value in enumerate(L):
    print(index,value)

0 a
1 b
2 c
3 d


In [23]:
for index, value in zip(range(len(L)), L):
    print(index,value)

0 a
1 b
2 c
3 d


In [24]:
dict(zip(L1, L2))

{'a': 'd', 'b': 'e', 'c': 'f'}

In [25]:
zipped = list(zip(L1, L2, L3))

In [26]:
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [27]:
list(zip(*zipped))

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

## 2.1 np数组的构造

In [29]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

### 2.1.1 等差数列使用np.linespace, np.arange

In [30]:
np.linspace(1,5,11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [31]:
np.arange(1,5,2)

array([1, 3])

### 2.1.2 zeros,eye,full矩阵

In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [37]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [38]:
np.full((2,3),[1,2,3])

array([[1, 2, 3],
       [1, 2, 3]])

### 2.1.3 随机矩阵：np.random

In [40]:
np.random.rand(3)

array([0.57516637, 0.55655425, 0.23292903])

In [41]:
np.random.rand(3,3)

array([[0.79545689, 0.23844725, 0.70692515],
       [0.09225148, 0.04828127, 0.54883389],
       [0.1099618 , 0.45887292, 0.36974984]])

In [42]:
a, b = 5, 15
(b - a) * np.random.rand(3) + a

array([13.49939081,  5.62291608,  5.42195067])

In [43]:
np.random.randn(3)

array([-0.5205505 , -0.21960652,  0.27090357])

In [44]:
np.random.randn(2, 2)

array([[-0.01625008,  0.82126033],
       [-1.98918739,  0.77143005]])

In [2]:
import numpy as np
sigma, mu = 2.5, 3
mu + np.random.randn(3) * sigma

array([ 3.96574544, -1.95630109,  2.90965696])

In [3]:
low, high, size = 5, 15, (2,2)
np.random.randint(low, high, size)

array([[ 5,  7],
       [ 8, 11]])

In [4]:
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])


array(['b', 'a'], dtype='<U1')

In [6]:
np.random.choice(my_list, (3,3))

array([['a', 'c', 'b'],
       ['c', 'd', 'a'],
       ['d', 'c', 'd']], dtype='<U1')

In [7]:
np.random.permutation(my_list)

array(['a', 'c', 'b', 'd'], dtype='<U1')

In [8]:
np.random.seed(0)

In [9]:
np.random.rand()

0.5488135039273248

## 2.2 np数组的变形与合并

In [10]:
 np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.r_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

r竟然是上下合并，c是左右合并，为啥啊？

In [12]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
try:
    np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
    Err_Msg = e

In [16]:
Err_Msg

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

In [17]:
np.r_[np.array([0,0]),np.zeros(2)]

array([0., 0., 0., 0.])

In [18]:
np.c_[np.array([0,0]),np.zeros((2,3))]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
target = np.arange(8).reshape(2,4)
target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
target.reshape((4,2), order='C') # 按照行读取和填充

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

C是行，F是列又是为啥啊？

In [21]:
target.reshape((4,2), order='F') # 按照列读取和填充

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In [22]:
target.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [23]:
target = np.ones((3,1))

In [24]:
target.reshape(-1)

array([1., 1., 1.])

？？？？？为啥-1就变成一行了？

## 2.3 np数组的切片与索引

In [25]:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
target[:-1, [0,2]]

array([[0, 2],
       [3, 5]])

:-1这个格式蛮有意思

In [27]:
target[np.ix_([True, False, True], [True, False, True])]

array([[0, 2],
       [6, 8]])

In [28]:
target[np.ix_([1,2], [True, False, True])]

array([[3, 5],
       [6, 8]])

In [30]:
new = target.reshape(-1)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

原来-1的意思就是变成一行啊

In [31]:
new[new%2==0]

array([0, 2, 4, 6, 8])

## 2.4 常用函数

In [33]:
a = np.array([-1,1,-1,0])
np.where(a>0, a, 5)

array([5, 1, 5, 5])

In [34]:
a = np.array([-2,-5,0,1,3,-1])

In [35]:
np.nonzero(a)

(array([0, 1, 3, 4, 5], dtype=int64),)

In [36]:
a.argmax()

4

In [37]:
a.argmin()

1

记住返回的是索引

In [38]:
a = np.array([0,1])

In [39]:
a.any()

True

In [40]:
a.all()

False

In [41]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [42]:
 a.cumprod()

array([1, 2, 6], dtype=int32)

In [43]:
a.cumsum()

array([1, 3, 6], dtype=int32)

In [44]:
np.diff(a)

array([1, 1])

In [46]:
target = np.arange(5)
target

array([0, 1, 2, 3, 4])

In [47]:
target.max()

4

In [48]:
np.quantile(target, 0.5) # 0.5分位数

2.0

In [50]:
target = np.array([1, 2, np.nan])
target

array([ 1.,  2., nan])

In [51]:
target.max()

nan

In [52]:
np.nanmax(target)

2.0

In [53]:
np.nanquantile(target, 0.5)

1.5

nan*函数！！！

In [55]:
target1 = np.array([1,3,5,9])
target2 = np.array([1,5,3,-9])

In [56]:
np.cov(target1, target2)

array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

In [57]:
np.corrcoef(target1, target2)

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

In [59]:
target = np.arange(1,10).reshape(3,-1)
target

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

这个reshape的-1也太有用了

In [62]:
target.sum(0)

array([12, 15, 18])

In [63]:
target.sum(1)

array([ 6, 15, 24])

0是列，1是行

## 2.5 广播机制

In [65]:
res = 3 * np.ones((2,2)) + 1
res

array([[4., 4.],
       [4., 4.]])

In [68]:
res = 1 / res
res

array([[0.25, 0.25],
       [0.25, 0.25]])

In [70]:
res = np.ones((3,2))
res

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [71]:
res * np.array([[2,3]])

array([[2., 3.],
       [2., 3.],
       [2., 3.]])

In [73]:
res * np.array([[2],[3],[4]])

array([[2., 2.],
       [3., 3.],
       [4., 4.]])

In [74]:
res * np.array([[2]])

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [75]:
np.ones(3) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [76]:
np.ones(3) + np.ones((2,1))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [77]:
np.ones(1) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

## 2.6 向量与矩阵的计算

In [79]:
a = np.array([1,2,3])
b = np.array([1,3,5])
a.dot(b)

22

In [80]:
martix_target =  np.arange(4).reshape(-1,2)
martix_target

array([[0, 1],
       [2, 3]])

In [81]:
np.linalg.norm(martix_target, 'fro')

3.7416573867739413

In [82]:
np.linalg.norm(martix_target, np.inf)

5.0

In [83]:
np.linalg.norm(martix_target, 2)

3.702459173643833

In [85]:
vector_target =  np.arange(4)
vector_target

array([0, 1, 2, 3])

In [86]:
np.linalg.norm(vector_target, np.inf)

3.0

In [87]:
np.linalg.norm(vector_target, 2)

3.7416573867739413

In [88]:
np.linalg.norm(vector_target, 3)

3.3019272488946263

In [90]:
a = np.arange(4).reshape(-1,2)
a

array([[0, 1],
       [2, 3]])

In [92]:
b = np.arange(-4,0).reshape(-1,2)
b

array([[-4, -3],
       [-2, -1]])

In [93]:
a@b

array([[ -2,  -1],
       [-14,  -9]])

# 3.练习

## 3.1利用列表推导式写矩阵乘法

In [3]:
import numpy as np 
M1 = np.random.randn(2,3)
M2 = np.random.randn(3,4)
[[sum([M1[i, k]*M2[k,j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])] for i in range(M1.shape[0])]

[[-0.00888643048812024,
  -0.5904374000743217,
  -0.40737197926717117,
  -0.4146085546693448],
 [-1.2375055651751092,
  -1.1778332647765066,
  -0.9533383348073688,
  1.4182305889728608]]

## 3.2更新矩阵

In [2]:
import numpy as np
A = np.arange(1,10).reshape(3,-1)
B = A*(1/A).sum(1).reshape(-1,1)

## 3.3卡方统计量

In [3]:
B = A.sum(0)*A.sum(1).reshape(-1, 1)/A.sum()
chi2 = ((A-B)**2/B).sum()

## 3.4改进矩阵计算的性能

In [5]:
def answer():
    L_res= ((np.ones((m, n)) * (B ** 2).sum(1).reshape(-1, 1) + np.ones((m, n)) * (U ** 2).sum(0) - 2 * B @ U) * Z).sum()


## 3.5连续整数最大长度

In [6]:
a = np.array([1,2,5,6,7])
np.r_[1,np.diff(a)!=1,1]

array([1, 0, 1, 0, 0, 1], dtype=int32)